[package]
name = "mkfs"
description = "mkfs xv6 mleko-os fs"
version.workspace = true
edition = "2021"
repository.workspace = true
license.workspace = true
authors = ["Amarnath Patel <apatel6ty@protonmail.com>"]

[[bin]]
name = "mkfs"
path = "main.rs"

[dependencies]
libkernel = {workspace = true}